### ISSUE TITLE
Can not download Maven Dependencies hosted with GitHub Packages

### ISSUE THREAD

**Issue by qOEJXOT4** [UOC/java-lti-1.3-provider-example#7]
Hello,

I have heard from different people that they can not download the maven dependencies in this project
using their github private access token because they are getting 401 unauthorized error.
Maybe this has something to do with permissions, so you could check if you can do this with another GitHub account
not associated with this project.

Thanks in advance

**Comment by xaviaracil** [comment]
Updated pom.xml with repository info. Please pull your repo, it should work now.

**Comment by qOEJXOT4** [comment]
Thanks for the quick reply. Unfortunately the error still exists.

The workaround I used before was to pull each repo from GitHub seperately and mvn install it.
To do so I had to update lombok in the following manner in each repo:
<dependency>
<groupId>org.projectlombok</groupId>
<artifactId>lombok</artifactId>
<version>1.18.22</version>
</dependency>

Here is my current error:
[ERROR] Failed to execute goal on project provider: Could not resolve dependencies for project edu.uoc.elearn.lti:provider:jar:0.0.4-SNAPSHOT: Failed to collect dependencies at edu.uoc.elc.lti:spring-boot-lti-advantage:jar:0.0.10: Failed to read artifact descriptor for edu.uoc.elc.lti:spring-boot-lti-advantage:jar:0.0.10: Could not transfer artifact edu.uoc.elc.lti:spring-boot-lti-advantage:pom:0.0.10 from/to github-uoc-lti-core (https://maven.pkg.github.com/uoc/java-lti-1.3-core): Not authorized -> [Help 1]

**Comment by pvharish** [comment]
I am able to build the project successfully, but when I run it locally- I am getting error in UI screen as Access Denied and status code : 403 forbidden error. How to fix it, any extra configurations are required ? I just did setup of provider-example project and while doing mvn install, it has downloaded all the dependency project jars like jwt,core,lti-advantage etc

**Comment by xaviaracil** [comment]
How are you accessing the tool? It should be accessed through an LMS, and the tool must be configured with that LMS
