### ISSUE TITLE
Missing OIDC Login Initiation URI and OIDC Redirct URIs

### ISSUE THREAD

**Issue by qOEJXOT4** [UOC/java-lti-1.3-provider-example#8]
Hello,

is this project still in development? I can not find the mandatory URIs for LTI 1.3.

Thanks in Advance

**Comment by xaviaracil** [comment]
Hello,

I'm currenlty evolving this development with upcoming features of LTI. Configurable parameters are defined in  application.yml files (see https://github.com/UOC/java-lti-1.3-provider-example/blob/master/src/main/resources/application-cert.yml for an example).

This project relys on the https://github.com/UOC/spring-boot-lti-advantage library, which defines the OIDC uri (https://github.com/UOC/spring-boot-lti-advantage/blob/master-github/src/main/java/edu/uoc/elc/spring/lti/security/LTIApplicationSecurity.java).

Take into account that this example project is a webapp, so the final URI will depen on where you'll deploy the webapp.

**Comment by qOEJXOT4** [comment]
Thank you, this solved my issue.
